-- ============================================================
-- MUSCLE MEALS — Import: Ingredientes
-- Actualizado: 2026-03-13
-- Solo actualiza ingredientes existentes por nombre.
-- No crea nuevos ni borra nada.
-- PREREQUISITO: columnas numeric(7,2) ya corridas en Supabase.
-- ============================================================

UPDATE ingredients SET type='pro',  calories=120.00, protein=22.50, carbs=0.00,   fats=2.60,  unit='g',   cant=1000, precio=78.00,   public_name='Pechuga de Pollo',                          proveedor='La Hacienda'    WHERE name='Pechuga de Pollo';
UPDATE ingredients SET type='pro',  calories=115.00, protein=21.20, carbs=0.00,   fats=4.00,  unit='g',   cant=690,  precio=196.00,  public_name='Carne Molida',                              proveedor='Grill House Mty' WHERE name='Carne Molida 97';
UPDATE ingredients SET type='pro',  calories=137.00, protein=21.30, carbs=0.00,   fats=5.00,  unit='g',   cant=690,  precio=196.00,  public_name='Carne Molida',                              proveedor='Grill House Mty' WHERE name='Carne Molida 95';

UPDATE ingredients SET type='carb', calories=375.00, protein=11.00, carbs=76.00,  fats=1.00,  unit='g',   cant=200,  precio=7.00,    public_name='Pasta',                                     proveedor='HEB'            WHERE name='Pasta Tornillo';
UPDATE ingredients SET type='carb', calories=375.00, protein=11.00, carbs=76.00,  fats=1.00,  unit='g',   cant=200,  precio=7.00,    public_name='Pasta',                                     proveedor='HEB'            WHERE name='Pasta Pluma';
UPDATE ingredients SET type='carb', calories=375.00, protein=11.00, carbs=76.00,  fats=1.00,  unit='g',   cant=200,  precio=7.00,    public_name='Pasta',                                     proveedor='HEB'            WHERE name='Pasta Linguini';
UPDATE ingredients SET type='carb', calories=348.00, protein=7.00,  carbs=80.00,  fats=0.00,  unit='g',   cant=1000, precio=28.90,   public_name='Arroz Blanco',                              proveedor='HEB'            WHERE name='Arroz Super Extra';
UPDATE ingredients SET type='carb', calories=361.00, protein=10.70, carbs=69.60,  fats=3.60,  unit='g',   cant=500,  precio=44.00,   public_name='Fideo de Ramen',                            proveedor='TOYO'           WHERE name='Fideo Ramen';

UPDATE ingredients SET type='veg',  calories=34.00,  protein=2.80,  carbs=4.00,   fats=0.40,  unit='g',   cant=1130, precio=124.00,  public_name='Brocoli',                                   proveedor='HEB'            WHERE name='Vegetales Congelados Brocoli';
UPDATE ingredients SET type='veg',  calories=45.00,  protein=2.40,  carbs=10.20,  fats=0.60,  unit='g',   cant=1000, precio=42.95,   public_name='Chile Poblano',                             proveedor='HEB'            WHERE name='Chile Poblano';
UPDATE ingredients SET type='veg',  calories=31.00,  protein=2.00,  carbs=4.30,   fats=0.20,  unit='g',   cant=1000, precio=66.90,   public_name='Ejote Verde',                               proveedor='COSTCO'         WHERE name='Ejote Verde';
UPDATE ingredients SET type='veg',  calories=21.00,  protein=2.90,  carbs=1.40,   fats=0.40,  unit='g',   cant=284,  precio=59.00,   public_name='Espinaca',                                  proveedor='COSTCO'         WHERE name='Espinaca';
UPDATE ingredients SET type='veg',  calories=40.00,  protein=1.10,  carbs=7.60,   fats=0.10,  unit='g',   cant=1000, precio=75.63,   public_name='Mix de Cebolla y Pimientos',                proveedor='HEB'            WHERE name='Mix de Cebolla Blanca y Pimientos';
UPDATE ingredients SET type='veg',  calories=50.00,  protein=1.70,  carbs=9.70,   fats=0.70,  unit='g',   cant=262,  precio=21.00,   public_name='Elote',                                     proveedor='HEB'            WHERE name='Elote en Lata';
UPDATE ingredients SET type='veg',  calories=23.00,  protein=17.00, carbs=19.10,  fats=0.20,  unit='g',   cant=1000, precio=29.95,   public_name='Calabacita',                                proveedor='HEB'            WHERE name='Calabacita';
UPDATE ingredients SET type='veg',  calories=140.00, protein=11.00, carbs=7.00,   fats=5.00,  unit='g',   cant=340,  precio=73.00,   public_name='Edamame',                                   proveedor='HEB'            WHERE name='edamames congelados';
UPDATE ingredients SET type='veg',  calories=30.00,  protein=2.00,  carbs=7.20,   fats=0.00,  unit='g',   cant=2500, precio=111.51,  public_name='Mix de Borocoli, Zanahoria y Castañas',     proveedor='HEB'            WHERE name='Verduras Ramen Congeladas';
UPDATE ingredients SET type='veg',  calories=24.00,  protein=2.40,  carbs=1.20,   fats=0.00,  unit='pz',  cant=1,    precio=14.95,   public_name='Cilantro',                                  proveedor='HEB'            WHERE name='Cilantro Manojo';
UPDATE ingredients SET type='veg',  calories=34.00,  protein=1.40,  carbs=5.50,   fats=0.40,  unit='g',   cant=1000, precio=29.95,   public_name='Jalapeño',                                  proveedor='HEB'            WHERE name='Chile Jalapeño';
UPDATE ingredients SET type='veg',  calories=45.00,  protein=3.00,  carbs=7.70,   fats=1.30,  unit='pz',  cant=1,    precio=15.50,   public_name='Perejil',                                   proveedor='HEB'            WHERE name='Perejil Liso Manojo';
UPDATE ingredients SET type='veg',  calories=23.00,  protein=3.20,  carbs=2.70,   fats=0.60,  unit='pz',  cant=1,    precio=36.00,   public_name='Albahaca',                                  proveedor='HEB'            WHERE name='Albahaca Empacada';
UPDATE ingredients SET type='veg',  calories=32.00,  protein=1.80,  carbs=7.30,   fats=0.00,  unit='pz',  cant=1,    precio=36.00,   public_name='Cebollin',                                  proveedor='HEB'            WHERE name='Cebollin Empacada';
UPDATE ingredients SET type='veg',  calories=16.00,  protein=1.00,  carbs=3.00,   fats=0.00,  unit='g',   cant=500,  precio=83.00,   public_name='Rajas',                                     proveedor='HEB'            WHERE name='Rajas Poblano';
UPDATE ingredients SET type='veg',  calories=30.00,  protein=1.00,  carbs=6.80,   fats=0.00,  unit='g',   cant=500,  precio=48.50,   public_name='Mix de Zanahoria, Elote, Papa y Chicharo',  proveedor='HEB'            WHERE name='Verduras Congelados Primavera';
UPDATE ingredients SET type='veg',  calories=32.00,  protein=0.00,  carbs=3.60,   fats=0.00,  unit='g',   cant=1000, precio=67.50,   public_name='Tomatillo Verde',                           proveedor='HEB'            WHERE name='Tomatillo Verde';
UPDATE ingredients SET type='veg',  calories=32.00,  protein=1.70,  carbs=10.40,  fats=0.40,  unit='g',   cant=1000, precio=41.50,   public_name='Chile Serrano',                             proveedor='HEB'            WHERE name='Chile Serrano';
UPDATE ingredients SET type='veg',  calories=18.00,  protein=0.88,  carbs=3.92,   fats=0.20,  unit='g',   cant=1000, precio=36.00,   public_name='Tomate Rojo',                               proveedor='HEB'            WHERE name='Tomate Huaje';
UPDATE ingredients SET type='veg',  calories=40.00,  protein=1.10,  carbs=9.30,   fats=0.10,  unit='g',   cant=1000, precio=20.50,   public_name='Cebolla Blanca',                            proveedor='HEB'            WHERE name='cebolla blanca';

UPDATE ingredients SET type=null,   calories=318.00, protein=12.00, carbs=29.40,  fats=17.30, unit='g',   cant=100,  precio=1.00,    public_name='Pimienta Cayenna',              proveedor='HEB'            WHERE name='Pimienta cayenna';
UPDATE ingredients SET type=null,   calories=152.00, protein=6.80,  carbs=2.50,   fats=14.20, unit='g',   cant=1000, precio=133.00,  public_name='Ajonjoli',                      proveedor='HEB'            WHERE name='Ajonjoli';
UPDATE ingredients SET type=null,   calories=362.00, protein=11.00, carbs=56.00,  fats=11.00, unit='g',   cant=116,  precio=99.00,   public_name='Sasonador de Hierbas Finas',    proveedor='COSTCO'         WHERE name='Hierbas Finas Sasonador';
UPDATE ingredients SET type=null,   calories=0.00,   protein=0.00,  carbs=0.00,   fats=0.00,  unit='g',   cant=400,  precio=155.00,  public_name='Paprika',                       proveedor='COSTCO'         WHERE name='Paprika';
UPDATE ingredients SET type=null,   calories=318.00, protein=12.00, carbs=29.40,  fats=17.30, unit='g',   cant=368,  precio=169.00,  public_name='Piento Rojo Triturado',         proveedor='AMAZON'         WHERE name='Pimenton Rojo Triturado';
UPDATE ingredients SET type=null,   calories=0.00,   protein=0.00,  carbs=0.00,   fats=0.00,  unit='g',   cant=560,  precio=191.00,  public_name='Ajo en Polvo',                  proveedor='COSTCO'         WHERE name='Ajo en Polvo';
UPDATE ingredients SET type=null,   calories=251.00, protein=10.40, carbs=38.70,  fats=3.30,  unit='g',   cant=425,  precio=269.00,  public_name='Pimienta Negra Molida',         proveedor='COSTCO'         WHERE name='Pimienta negra';
UPDATE ingredients SET type=null,   calories=0.00,   protein=0.00,  carbs=0.00,   fats=0.00,  unit='g',   cant=1000, precio=23.00,   public_name='Sal en Grano',                  proveedor='COSTCO'         WHERE name='Sal en grano';
UPDATE ingredients SET type=null,   calories=157.00, protein=4.80,  carbs=29.40,  fats=0.50,  unit='g',   cant=400,  precio=165.00,  public_name='Cebolla en Polvo',              proveedor='HEB'            WHERE name='Cebolla en polvo';
UPDATE ingredients SET type=null,   calories=0.00,   protein=0.00,  carbs=0.00,   fats=0.00,  unit='g',   cant=127,  precio=53.50,   public_name='Blackened Seasoning',           proveedor='HEB'            WHERE name='Blackened Seasoning HEB';
UPDATE ingredients SET type=null,   calories=6.00,   protein=0.20,  carbs=0.60,   fats=0.10,  unit='g',   cant=290,  precio=142.00,  public_name='Oregano Seco',                  proveedor='AMAZON'         WHERE name='Oregano Seco';
UPDATE ingredients SET type=null,   calories=6.00,   protein=0.20,  carbs=0.60,   fats=0.10,  unit='g',   cant=535,  precio=184.00,  public_name='Comino Molido',                 proveedor='AMAZON'         WHERE name='Comino Molido';
UPDATE ingredients SET type=null,   calories=125.00, protein=0.00,  carbs=0.00,   fats=0.00,  unit='g',   cant=1500, precio=201.75,  public_name='Consome de Pollo',              proveedor='COSTCO'         WHERE name='Consome de Pollo Knorr';
UPDATE ingredients SET type=null,   calories=0.00,   protein=0.00,  carbs=0.00,   fats=0.00,  unit='g',   cant=510,  precio=62.90,   public_name='Sal de Cebolla en Polvo',       proveedor='HEB'            WHERE name='Sal de Cebolla en Polvo';
UPDATE ingredients SET type=null,   calories=540.00, protein=0.70,  carbs=0.70,   fats=60.00, unit='g',   cant=226,  precio=58.00,   public_name='Mantequilla Light',             proveedor='HEB'            WHERE name='Mantequilla Light';

UPDATE ingredients SET type=null,   calories=800.00, protein=0.00,  carbs=0.00,   fats=93.30, unit='ml',  cant=3000, precio=499.00,  public_name='Aceite de Oliva',               proveedor='COSTCO'         WHERE name='Aceite de Oliva';
UPDATE ingredients SET type=null,   calories=900.00, protein=0.00,  carbs=0.00,   fats=100.00,unit='ml',  cant=500,  precio=145.00,  public_name='Aceite de Ajonjoli',            proveedor='HEB'            WHERE name='Aceite de Ajonjoli';
UPDATE ingredients SET type=null,   calories=19.00,  protein=0.00,  carbs=0.30,   fats=0.00,  unit='ml',  cant=500,  precio=69.90,   public_name='Vinagre Rojo',                  proveedor='HEB'            WHERE name='Red Wine Vinegar';
UPDATE ingredients SET type=null,   calories=0.00,   protein=0.00,  carbs=0.00,   fats=0.00,  unit='ml',  cant=500,  precio=73.00,   public_name='Vinagre Blanco',                proveedor='HEB'            WHERE name='White Wine Vinegar';
UPDATE ingredients SET type=null,   calories=0.00,   protein=0.00,  carbs=0.00,   fats=0.00,  unit='ml',  cant=296,  precio=54.00,   public_name='Vinagre de Arroz',              proveedor='KOYO'           WHERE name='Vinagre de Arroz';
UPDATE ingredients SET type=null,   calories=21.00,  protein=0.00,  carbs=0.90,   fats=0.00,  unit='ml',  cant=1000, precio=177.00,  public_name='Vinagre de Manzana',            proveedor='HEB'            WHERE name='Vinagre de Manzana';
UPDATE ingredients SET type=null,   calories=53.00,  protein=4.00,  carbs=8.70,   fats=0.00,  unit='ml',  cant=500,  precio=122.00,  public_name='Salsa de Soya',                 proveedor='KOYO'           WHERE name='Salsa de Soya';
UPDATE ingredients SET type=null,   calories=18.00,  protein=0.00,  carbs=0.00,   fats=0.00,  unit='ml',  cant=150,  precio=34.50,   public_name='Mirin Vino de Arroz',           proveedor='HEB'            WHERE name='Mirin Vino de Arroz';
UPDATE ingredients SET type=null,   calories=44.00,  protein=5.40,  carbs=3.40,   fats=1.00,  unit='ml',  cant=1000, precio=42.00,   public_name='Leche Deslactosada',            proveedor='COSTCO'         WHERE name='Leche Lala Light Protina+';
UPDATE ingredients SET type=null,   calories=129.00, protein=2.70,  carbs=4.70,   fats=11.00, unit='ml',  cant=980,  precio=69.00,   public_name='Media Crema',                   proveedor='HEB'            WHERE name='Crema Half And Half lyncott';
UPDATE ingredients SET type=null,   calories=500.00, protein=16.00, carbs=48.00,  fats=12.00, unit='ml',  cant=500,  precio=44.90,   public_name='Salsa de Chile Colorado',       proveedor='HEB'            WHERE name='Chile Colorado (Enchilada Sauce)';

UPDATE ingredients SET type=null,   calories=60.00,  protein=10.30, carbs=4.00,   fats=0.00,  unit='g',   cant=907,  precio=265.00,  public_name='Yogurt Griego',                 proveedor='COSTCO'         WHERE name='Yogurt Griego 0% Fage';
UPDATE ingredients SET type=null,   calories=82.00,  protein=10.90, carbs=4.50,   fats=1.40,  unit='g',   cant=680,  precio=77.00,   public_name='Queso Cottage',                 proveedor='HEB'            WHERE name='Queso Cottage';
UPDATE ingredients SET type=null,   calories=467.00, protein=36.30, carbs=7.70,   fats=32.30, unit='g',   cant=680,  precio=203.58,  public_name='Queso Parmesano Molido',        proveedor='COSTCO'         WHERE name='Parmesano Grounded';
UPDATE ingredients SET type=null,   calories=404.00, protein=22.90, carbs=3.10,   fats=33.30, unit='g',   cant=907,  precio=102.20,  public_name='Queso Cheddar',                 proveedor='COSTCO'         WHERE name='Queso Cheddar en bloque';
UPDATE ingredients SET type=null,   calories=176.00, protein=3.20,  carbs=4.30,   fats=16.50, unit='g',   cant=190,  precio=22.00,   public_name='Queso Crema Reducido en Grasa', proveedor='HEB'            WHERE name='Queso Crema Reducido en Fat';
UPDATE ingredients SET type=null,   calories=286.00, protein=21.40, carbs=7.10,   fats=21.40, unit='g',   cant=454,  precio=151.00,  public_name='Queso Mozzarela',               proveedor='HEB'            WHERE name='queso mozzarela';
UPDATE ingredients SET type=null,   calories=427.00, protein=31.70, carbs=3.50,   fats=28.20, unit='g',   cant=300,  precio=172.00,  public_name='Queso Parmigiano-reggiano',     proveedor='HEB'            WHERE name='queso parmigiano-reggiano';
UPDATE ingredients SET type=null,   calories=500.00, protein=21.40, carbs=28.60,  fats=32.10, unit='g',   cant=100,  precio=1.00,    public_name='Queso Cheddar Molido',          proveedor='HEB'            WHERE name='Queso Cheddar en polvo';
UPDATE ingredients SET type=null,   calories=90.00,  protein=9.00,  carbs=2.00,   fats=5.00,  unit='g',   cant=425,  precio=135.00,  public_name='Queso Ricotta',                 proveedor='COSTCO'         WHERE name='Galbani Queso Ricotta';

UPDATE ingredients SET type=null,   calories=27.00,  protein=0.80,  carbs=6.00,   fats=0.00,  unit='g',   cant=170,  precio=20.50,   public_name='Pasta de Tomate',               proveedor='COSTCO'         WHERE name='Pasta de Tomate';
UPDATE ingredients SET type=null,   calories=274.00, protein=6.00,  carbs=99.00,  fats=13.00, unit='g',   cant=1000, precio=133.00,  public_name='Ajos',                          proveedor='COSTCO'         WHERE name='Ajo Cloves';
UPDATE ingredients SET type=null,   calories=80.00,  protein=0.00,  carbs=20.00,  fats=0.00,  unit='g',   cant=1000, precio=159.00,  public_name='Ajo Picado',                    proveedor='COSTCO'         WHERE name='Ajo Picado';
UPDATE ingredients SET type=null,   calories=110.00, protein=5.00,  carbs=12.00,  fats=5.00,  unit='g',   cant=226,  precio=13.90,   public_name='Mostaza',                       proveedor='COSTCO'         WHERE name='Mostaza';
UPDATE ingredients SET type=null,   calories=178.00, protein=0.40,  carbs=9.00,   fats=15.60, unit='g',   cant=800,  precio=79.00,   public_name='Mayonesa Light',                proveedor='COSTCO'         WHERE name='Mayonesa Light HELLMANS';
UPDATE ingredients SET type=null,   calories=324.00, protein=0.00,  carbs=81.00,  fats=0.00,  unit='g',   cant=350,  precio=41.90,   public_name='Miel de Abeja',                 proveedor='COSTCO'         WHERE name='Miel de Abeja';
UPDATE ingredients SET type=null,   calories=80.00,  protein=1.80,  carbs=20.00,  fats=0.80,  unit='g',   cant=1000, precio=184.00,  public_name='Jengibre',                      proveedor='HEB'            WHERE name='Jengibre';
UPDATE ingredients SET type=null,   calories=109.00, protein=5.10,  carbs=21.80,  fats=0.20,  unit='g',   cant=450,  precio=111.00,  public_name='Sriracha',                      proveedor='KOYO'           WHERE name='Sriracha';
UPDATE ingredients SET type=null,   calories=60.00,  protein=0.00,  carbs=15.00,  fats=0.00,  unit='g',   cant=420,  precio=57.50,   public_name='Salsa de Ostion',               proveedor='HEB'            WHERE name='Salsa de Ostion';
UPDATE ingredients SET type=null,   calories=101.00, protein=0.00,  carbs=20.30,  fats=0.00,  unit='ml',  cant=444,  precio=62.00,   public_name='Salsa Inglesa',                 proveedor='HEB'            WHERE name='Salsa Inglesa Worcestershire';
UPDATE ingredients SET type=null,   calories=155.00, protein=0.00,  carbs=38.80,  fats=0.00,  unit='g',   cant=320,  precio=54.00,   public_name='Salsa Agridulce',               proveedor='HEB'            WHERE name='Salsa Agridulce';
UPDATE ingredients SET type=null,   calories=10.00,  protein=0.50,  carbs=1.40,   fats=0.40,  unit='ml',  cant=355,  precio=259.00,  public_name='Salsa Picante',                 proveedor='COSTCO'         WHERE name='Tabasco Salsa Roja';
UPDATE ingredients SET type=null,   calories=27.00,  protein=1.10,  carbs=5.40,   fats=0.10,  unit='g',   cant=1000, precio=32.90,   public_name='Tomate Molido',                 proveedor='COSTCO'         WHERE name='Tomates Molidos Condimentados';
UPDATE ingredients SET type=null,   calories=113.00, protein=1.60,  carbs=6.50,   fats=8.10,  unit='g',   cant=425,  precio=56.50,   public_name='Salsa Alfredo',                 proveedor='HEB'            WHERE name='Salsa para Pasta Alfredo Parmesano y Romano';
UPDATE ingredients SET type=null,   calories=64.00,  protein=1.60,  carbs=7.20,   fats=2.00,  unit='g',   cant=439,  precio=49.90,   public_name='Salsa de Ajo Asado',            proveedor='HEB'            WHERE name='Salsa Para Pasta Ajo Asado';
UPDATE ingredients SET type=null,   calories=56.00,  protein=2.40,  carbs=5.60,   fats=2.00,  unit='g',   cant=737,  precio=72.00,   public_name='Salsa de Espinaca y Queso',     proveedor='HEB'            WHERE name='Salsa Para Pasta Espinacas Y Queso';
UPDATE ingredients SET type=null,   calories=48.00,  protein=0.80,  carbs=6.00,   fats=2.00,  unit='g',   cant=298,  precio=34.00,   public_name='Crema de Chile Poblano',        proveedor='HEB'            WHERE name='Crema de Poblano';
UPDATE ingredients SET type=null,   calories=473.00, protein=10.00, carbs=33.30,  fats=33.40, unit='g',   cant=430,  precio=88.00,   public_name='Mole',                          proveedor='HEB'            WHERE name='Mole Doña Maria';
UPDATE ingredients SET type=null,   calories=40.00,  protein=2.00,  carbs=16.00,  fats=0.00,  unit='g',   cant=220,  precio=34.00,   public_name='Chile Chipotle',                proveedor='COSTCO'         WHERE name='Chile Chipotle';
UPDATE ingredients SET type=null,   calories=0.00,   protein=0.00,  carbs=100.00, fats=0.00,  unit='g',   cant=453,  precio=156.00,  public_name='Azucar Monkfruit Morena',       proveedor='HEB'            WHERE name='Zero Cal Monkfruit Azucar Morena';
UPDATE ingredients SET type=null,   calories=4.00,   protein=0.80,  carbs=0.40,   fats=0.00,  unit='g',   cant=946,  precio=53.17,   public_name='Caldo de Pollo',                proveedor='COSTCO'         WHERE name='Caldo de pollo';
UPDATE ingredients SET type=null,   calories=0.00,   protein=0.00,  carbs=0.00,   fats=0.00,  unit='g',   cant=443,  precio=51.90,   public_name='Jugo de Limon',                 proveedor='HEB'            WHERE name='jugo de limon';
UPDATE ingredients SET type=null,   calories=0.00,   protein=0.00,  carbs=0.00,   fats=0.00,  unit='g',   cant=1000, precio=0.01,    public_name='Agua',                          proveedor=null             WHERE name='Agua';
